"""Availability: who misses games, and which managers have been unlucky.

    python -m scripts.availability

Writes research/availability.md and data/draft/availability.parquet.

James's stated number one problem across sixteen years is availability, and
`variance_study.md` independently reached the same place from the other
direction: games missed reduce the mean directly, and the mean is what pays,
while weekly variance is worth almost nothing. This league has **no IR slot**,
so an injured player also occupies one of only seven bench spots all season.

## What "games played" means here

nflverse weekly stats carry one row per player per week in which he recorded
any participation. A 17-game season across 18 weeks means one bye, so **17 is a
full season** and appearances out of 17 is the availability measure.

Two honest limits, stated up front because they bound every number below:

1. **This cannot distinguish injury from benching, suspension, or being a
   backup.** A rookie who takes over in week 8 reads identically to a starter
   who tore an ACL in week 8. Restricting to seasons in which a player was
   fantasy-relevant (a points threshold) removes most but not all of that.
2. **Manager "injury luck" is measured on players they drafted**, so it credits
   or blames a manager for the whole season of a player he cut in week 3. It is
   a measure of draft-day luck, which is the thing the draft engine can
   actually act on, not of in-season management.
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.config import get_canonical_name  # noqa: E402
from src.draft.ids import player_key  # noqa: E402

WEEKLY = Path("data/draft/weekly_points.parquet")
DRAFTS = Path("data/draft_cache.json")
PROJ = Path("data/inputs/projections.csv")
OUT_MD = Path("research/availability.md")
OUT_PQ = Path("data/draft/availability.parquet")

FULL_SEASON = 17          # 18 weeks, one bye
RELEVANT_PPG = 6.0        # per-game scoring floor for "was actually playing"


def player_seasons(w: pd.DataFrame) -> pd.DataFrame:
    """Games played and per-game scoring, per player-season."""
    g = (w.groupby(["key_name", "name", "pos", "season"], as_index=False)
           .agg(games=("pts", "size"), pts=("pts", "sum")))
    g["ppg"] = (g.pts / g.games).round(2)
    g["missed"] = (FULL_SEASON - g.games).clip(lower=0)
    return g


def main() -> int:
    w = pd.read_parquet(WEEKLY)
    seasons = sorted(w.season.unique())
    ps = player_seasons(w)

    # Only seasons in which the player was actually a contributor; otherwise
    # backups and mid-season call-ups read as "injured".
    rel = ps[ps.ppg >= RELEVANT_PPG].copy()

    L = [f"# Availability ({seasons[0]}–{seasons[-1]})\n",
         "*Generated by `python -m scripts.availability`. A full season is 17 "
         "games. Restricted to player-seasons averaging "
         f"{RELEVANT_PPG}+ points per game, so that backups and call-ups are "
         "not counted as injuries.*\n"]

    # ------------------------------------------------------------ setup
    # Base rates must come from players who were EXPECTED to start, otherwise
    # a backup quarterback who starts three games at a decent clip reads as an
    # injured starter. Rounds 1-8 of this room's own drafts is that population.
    drafts = pd.DataFrame(json.loads(DRAFTS.read_text())["drafts"])
    drafts["mgr"] = [get_canonical_name(p, m)
                     for p, m in zip(drafts.platform, drafts.manager)]
    drafts = drafts[drafts.season.isin(seasons) & (drafts["round"] <= 8)
                    & drafts.position.isin(["QB", "RB", "WR", "TE"])].copy()
    drafts["key_name"] = [player_key(n, p) for n, p
                          in zip(drafts.player_name, drafts.position)]
    ps_idx = ps.set_index(["key_name", "season"])

    drafted_games = defaultdict(list)
    for _, r in drafts.iterrows():
        try:
            rec = ps_idx.loc[(r.key_name, r.season)]
        except KeyError:
            continue
        if isinstance(rec, pd.DataFrame):
            rec = rec.iloc[0]
        drafted_games[r.position].append(rec.games)
    base_drafted = {p: round(float(pd.Series(v).mean()), 2)
                    for p, v in drafted_games.items() if v}

    # ---------------------------------------------------------------- 1
    L.append("## Base rates by position\n")
    L.append("This replaces the hardcoded `EXPECTED_GAMES` in `src/draft/data.py`, "
             "which was a guess.\n")
    L.append("Measured over **players actually drafted in rounds 1-8 of this "
             "league** — the population that was expected to start. Using all "
             "fantasy-relevant player-seasons instead put QB at 10.3 games, "
             "which is not an injury rate: it is backup quarterbacks clearing "
             "a per-game threshold across a handful of starts.\n")
    L.append("| pos | drafted seasons | mean games | median | P(16+) | P(<12) |")
    L.append("|---|---|---|---|---|---|")
    base = {}
    for pos in ("QB", "RB", "WR", "TE"):
        v = pd.Series(drafted_games.get(pos, []), dtype=float)
        if v.empty:
            continue
        base[pos] = round(float(v.mean()), 2)
        L.append(f"| {pos} | {len(v)} | **{v.mean():.2f}** | "
                 f"{v.median():.0f} | {(v >= 16).mean()*100:.0f}% | "
                 f"{(v < 12).mean()*100:.0f}% |")
    L.append("")
    L.append("```python\nEXPECTED_GAMES = " + json.dumps(base) + "\n```\n")

    # ---------------------------------------------------------------- 2
    L.append("## Most and least durable, of players who matter in 2026\n")
    car = (rel.groupby(["key_name", "name", "pos"], as_index=False)
              .agg(seasons=("season", "nunique"), games=("games", "sum"),
                   missed=("missed", "sum")))
    car["avail"] = (car.games / (car.seasons * FULL_SEASON)).round(3)
    car = car[car.seasons >= 2]

    if PROJ.exists():
        pr = pd.read_csv(PROJ)
        pr["key_name"] = [player_key(n, p) for n, p in zip(pr["name"], pr.pos)]
        # Positional caps, not an overall top-120: an overall cut leaves in
        # backup QBs (whose projections are low but whose ROLE is the reason,
        # not fragility) and drops startable tight ends.
        caps = {"QB": 16, "RB": 40, "WR": 50, "TE": 16}
        board = pd.concat([pr[pr.pos == k].nlargest(v, "proj")
                           for k, v in caps.items()])[["key_name", "proj"]]
        j = car.merge(board, on="key_name", how="inner")
        for label, sub, asc in (("Most durable", j.nlargest(10, "avail"), False),
                                ("Least durable", j.nsmallest(10, "avail"), True)):
            L.append(f"**{label}** (startable in 2026 — QB16/RB40/WR50/TE16 "
                     f"by projection — with 2+ seasons of history)\n")
            L.append("| player | pos | seasons | games | availability |")
            L.append("|---|---|---|---|---|")
            for _, r in sub.iterrows():
                L.append(f"| {r['name']} | {r.pos} | {r.seasons} | "
                         f"{int(r.games)}/{int(r.seasons*FULL_SEASON)} | "
                         f"**{r.avail*100:.0f}%** |")
            L.append("")

    # ---------------------------------------------------------------- 3
    L.append("## Manager injury luck\n")
    L.append("Games missed by the players each manager **drafted**, over the "
             f"seasons for which player-level data exists ({seasons[0]}–"
             f"{seasons[-1]}). Restricted to each manager's first eight picks — "
             "the ones intended as starters — so that late fliers do not "
             "dominate.\n")

    L.append("Expected games per drafted starter, by position (the reference "
             "population is drafted starters themselves, not all NFL "
             "contributors): "
             + ", ".join(f"**{k}** {v}"
                         for k, v in sorted(base_drafted.items()))
             + ".\n")

    rows = []
    for mgr, g in drafts.groupby("mgr"):
        exp = act = 0.0
        n = 0
        deltas = []
        for _, r in g.iterrows():
            try:
                rec = ps_idx.loc[(r.key_name, r.season)]
            except KeyError:
                continue          # never played that season at all — not injury
            if isinstance(rec, pd.DataFrame):
                rec = rec.iloc[0]
            act += rec.games
            e = base_drafted.get(r.position, 15.0)
            exp += e
            deltas.append(rec.games - e)
            n += 1
        if n:
            d = pd.Series(deltas)
            se = float(d.std(ddof=1) / (n ** 0.5)) if n > 1 else float("nan")
            rows.append({"manager": mgr, "picks": n,
                         "expected": round(exp, 1), "actual": round(act, 1),
                         "delta": round(act - exp, 1),
                         "per_pick": round((act - exp) / n, 2),
                         "se": round(se, 2),
                         "t": round(((act - exp) / n) / se, 2) if se else 0.0})
    tab = pd.DataFrame(rows).sort_values("per_pick")
    L.append("| manager | picks | expected | actual | delta | per pick | ± SE | t |")
    L.append("|---|---|---|---|---|---|---|---|")
    for _, r in tab.iterrows():
        L.append(f"| {r['manager']} | {r.picks} | {r.expected:.0f} | "
                 f"{r.actual:.0f} | **{r.delta:+.0f}** | {r.per_pick:+.2f} | "
                 f"{r.se:.2f} | {r.t:+.2f} |")
    L.append("")
    worst, best = tab.iloc[0], tab.iloc[-1]
    L.append(f"Range: **{worst['manager']}** {worst.per_pick:+.2f} games per "
             f"drafted starter, **{best['manager']}** {best.per_pick:+.2f}. "
             f"Over eight starters that is a spread of "
             f"{abs(worst.per_pick - best.per_pick) * 8:.1f} games a season "
             f"between the unluckiest and the luckiest.\n")
    big = tab.t.abs().max()
    L.append(f"### None of this is statistically significant\n")
    L.append(f"The largest t-statistic in the table is **{big:.2f}**. With "
             f"~40 drafted starters per manager over five seasons, and a "
             f"standard deviation of roughly five games on any single player's "
             f"availability, the standard error on these per-pick figures is "
             f"~0.5 games — comparable to the effects themselves. **Nobody in "
             f"this room is measurably lucky or unlucky with injuries.**\n")
    L.append("That is a more useful answer than a ranking would be. The "
             "ordering is real in the sense that it happened, but it does not "
             "predict anything, and it should not be carried into 2026 as a "
             "belief about anyone's fortune — including one's own. Five "
             "seasons is simply too few.\n")
    L.append("**What IS actionable** is the per-player table above. Individual "
             "durability is measured on far more data than a manager's forty "
             "picks, and it is the input the draft can actually use: prefer the "
             "durable player when value is close, and price the fragile one "
             "down rather than hoping. With no IR slot, a player who misses six "
             "games costs a roster spot as well as the points.\n")
    L.append("Note also that drafting fragile players and being unlucky are "
             "indistinguishable in this table by construction. If a manager "
             "were persistently negative across many more seasons, the "
             "actionable reading would be that he keeps buying injury risk — "
             "not that the universe dislikes him.\n")

    # ---------------------------------------------------------------- 4
    L.append("## Is injury risk already priced into the projections?\n")
    L.append("Partly — and the part it misses is the part that matters.\n")
    L.append("A projection implies a number of games: divide it by the "
             "player's recent points-per-game and you get the games the "
             "projection is assuming. Comparing that to the games he has "
             "actually played says whether the forecaster has haircut him.\n")

    rec = w[w.season >= max(seasons) - 1]
    hist = (rec.groupby("key_name")
               .agg(games=("pts", "size"), pts=("pts", "sum"),
                    name=("name", "first"), pos=("pos", "first")).reset_index())
    hist["ns"] = rec.groupby("key_name").season.nunique().values
    hist = hist[(hist.ns == 2) & (hist.games >= 12)
                & (hist.pts / hist.games >= 5)].copy()
    hist["ppg"] = hist.pts / hist.games
    hist["hist_gps"] = hist.games / 2

    adj = pd.DataFrame()
    if PROJ.exists():
        pr2 = pd.read_csv(PROJ)
        pr2["key_name"] = [player_key(n, p) for n, p in zip(pr2.name, pr2.pos)]
        adj = hist.merge(pr2[["key_name", "proj"]], on="key_name", how="inner")
        adj["implied"] = adj.proj / adj.ppg
        adj["gap"] = adj.implied - adj.hist_gps
        adj["bucket"] = pd.cut(adj.hist_gps, [0, 12, 14, 16, 17.1],
                               labels=["<12 g/yr", "12–14", "14–16", "16–17"])
        L.append("| recent games/yr | n | actually played | projection assumes | gap |")
        L.append("|---|---|---|---|---|")
        for b, s in adj.groupby("bucket", observed=True):
            L.append(f"| {b} | {len(s)} | {s.hist_gps.mean():.1f} | "
                     f"{s.implied.mean():.1f} | **{s.gap.mean():+.1f}** |")
        L.append("")
        L.append("In aggregate the gap is near zero, which looks like a full "
                 "haircut. **It is not.** That average is carried by players "
                 "whose low games reflect a diminished ROLE — backups and "
                 "ageing veterans, whose projections are low for that reason. "
                 "Split out the players whose games were lost to injury while "
                 "their role stayed elite and the picture inverts:\n")
        L.append("| player | pos | recent games/yr | projection assumes | gap |")
        L.append("|---|---|---|---|---|")
        watch = adj[(adj.hist_gps < 13) & (adj.proj >= 180)].nlargest(8, "gap")
        for _, r in watch.iterrows():
            L.append(f"| {r['name']} | {r.pos} | {r.hist_gps:.1f} | "
                     f"{r.implied:.1f} | **{r.gap:+.1f}** |")
        L.append("")
        L.append("These are projected back to roughly a full season. Their "
                 "injury history is **not** priced in.\n")
        L.append("### The sensitivity\n")
        L.append("What the board looks like if each of these players simply "
                 "repeats his own recent availability. This is a stress test, "
                 "not a replacement board — the truth is somewhere between, "
                 "since players do recover and a two-season sample is thin.\n")
        L.append("| player | projection | if he plays at his own recent rate | loss |")
        L.append("|---|---|---|---|")
        for _, r in watch.iterrows():
            shrunk = r.proj * r.hist_gps / r.implied
            L.append(f"| {r['name']} | {r.proj:.0f} | **{shrunk:.0f}** | "
                     f"{shrunk - r.proj:+.0f} |")
        L.append("")
        L.append("**The one that decides a pick: Christian McCaffrey.** He is "
                 "the third most valuable player on the 2026 board, and the "
                 "gap between what his projection assumes and what he has "
                 "actually played is the difference between a top-three pick "
                 "and a mid-second-round one.\n")

    OUT_PQ.parent.mkdir(parents=True, exist_ok=True)
    if len(adj):
        adj.to_parquet(Path("data/draft/projection_games_gap.parquet"),
                       index=False)
    car.to_parquet(OUT_PQ, index=False)
    OUT_MD.write_text("\n".join(L))
    print(f"Wrote {OUT_MD} and {OUT_PQ}")
    print(tab.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
