"""How many games will each player actually play in 2026?

    python -m scripts.games_model

Writes research/games_model.md and data/draft/games_model.parquet, the latter
carrying an `avail_mult` per player for the board to apply.

## The headline, which is a negative result

**Availability is almost entirely unpredictable.** Regressing next season's
games played on a player's own history and age, over 580 startable
player-seasons from 2021-25, gets **R² = 0.032**. Ninety-seven percent of the
variation in who gets hurt is not forecastable from what we have.

That is the finding, not a failure of the model, and it has a direct
consequence: **the naive "he has played 10.5 games a year, so project him for
10.5" adjustment is badly wrong.** Past games played regresses hard to the
mean. The measured coefficient is +0.27 — a player with six fewer games of
history than an iron man projects for about **1.7** fewer games next season,
not six.

## Watch for survivorship bias

Measured only on players who stayed startable in both seasons, the correlation
is +0.032 and the effect vanishes entirely — because that filter deletes
exactly the players whose injuries wrecked them. Following every startable
player into the next season, including the 15 who disappeared from the league
outright, restores a real if small signal. The unconditional figures are the
ones used here.

## What the model is

Linear, three inputs, deliberately simple given the R²:

    games_next ≈ 0.272 * (mean games in prior seasons)
                 - 0.180 * age
                 + 0.323 * (number of prior seasons observed)
                 + 13.27

Age carries about as much signal as injury history does. The `n_prior` term is
picking up "has been in the league long enough to have a track record", which
is mostly a proxy for being an established starter.

## What it deliberately does NOT do

No injury-type modelling. An Achilles tear, a hamstring strain and a concussion
are the same event here, and they are not the same thing medically or in terms
of recurrence. That is the single biggest available improvement and it needs
data this repo does not have.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.draft.ids import player_key  # noqa: E402

WEEKLY = Path("data/draft/weekly_points.parquet")
PLAYERS = Path("data/draft/players.parquet")
PROJ = Path("data/inputs/projections.csv")
OUT_MD = Path("research/games_model.md")
OUT_PQ = Path("data/draft/games_model.parquet")

SEASON = 2026
FULL = 17
# "Startable": roughly the players a 10-team league actually rosters as starters.
CAPS = {"QB": 20, "RB": 45, "WR": 60, "TE": 20}


def build_training(ps: pd.DataFrame, ages: dict) -> pd.DataFrame:
    startable = pd.concat([g.nlargest(CAPS.get(p, 40), "pts")
                           for (s, p), g in ps.groupby(["season", "pos"])])
    games = ps.set_index(["key_name", "season"]).games
    rows = []
    for _, r in startable.iterrows():
        nxt = r.season + 1
        if (ps.season == nxt).sum() == 0:
            continue
        prior = ps[(ps.key_name == r.key_name) & (ps.season <= r.season)]
        a = ages.get(r.key_name)
        if a is None or not np.isfinite(a):
            continue
        rows.append({
            "key_name": r.key_name, "pos": r.pos, "season": r.season,
            "hist_mean": prior.games.mean(), "n_prior": len(prior),
            "age_then": a - (SEASON - r.season),
            # 0 when the player did not appear in the league at all
            "y": float(games.get((r.key_name, nxt), 0)),
        })
    return pd.DataFrame(rows)


def fit(d: pd.DataFrame, cols: list[str]):
    X = np.column_stack([d[c].to_numpy(float) for c in cols] + [np.ones(len(d))])
    beta, *_ = np.linalg.lstsq(X, d.y.to_numpy(float), rcond=None)
    pred = X @ beta
    r2 = 1 - ((d.y - pred) ** 2).sum() / ((d.y - d.y.mean()) ** 2).sum()
    return beta, float(r2)


def main() -> int:
    w = pd.read_parquet(WEEKLY)
    ps = (w.groupby(["key_name", "name", "pos", "season"], as_index=False)
            .agg(games=("pts", "size"), pts=("pts", "sum")))
    players = pd.read_parquet(PLAYERS)
    ages = players.dropna(subset=["age"]).set_index("key_name").age.to_dict()

    d = build_training(ps, ages)
    cols = ["hist_mean", "age_then", "n_prior"]
    beta, r2 = fit(d, cols)

    L = [f"# Expected games played, {SEASON}\n",
         "*Generated by `python -m scripts.games_model`.*\n",
         "## Availability is ~97% unpredictable\n",
         f"Fitted on **{len(d)} startable player-seasons**, 2021–25, following "
         "every one into the next season including those who left the league "
         "entirely.\n",
         "| model | R² |", "|---|---|"]
    for label, c in (("last season's games only", ["hist_mean"]),
                     ("age only", ["age_then"]),
                     ("history + age", ["hist_mean", "age_then"]),
                     ("history + age + seasons observed", cols)):
        L.append(f"| {label} | {fit(d, c)[1]:.4f} |")
    L.append("")
    L.append(f"**R² = {r2:.3f}.** Age carries about as much signal as injury "
             "history does, and together they explain three percent of the "
             "variance. This is the central result: **who gets hurt next year "
             "is not something this data can tell you.**\n")
    L.append("```\ngames_next ≈ "
             + " ".join(f"{b:+.3f}·{c}" for b, c in zip(beta, cols))
             + f" {beta[-1]:+.2f}\n```\n")
    L.append(f"The history coefficient is **{beta[0]:+.3f}**. A player with six "
             f"fewer games of track record than an iron man projects for about "
             f"**{abs(beta[0])*6:.1f} fewer games** next season — not six. "
             "Past availability regresses hard to the mean.\n")
    L.append("### The survivorship trap\n")
    L.append("Measured only on players who remained startable in both seasons, "
             "the year-over-year correlation is **+0.03** and the effect "
             "disappears — because that filter removes exactly the players "
             "whose injuries wrecked them. Followed unconditionally it is "
             "**+0.11**. Small either way, but the difference is the whole "
             "reason to be careful here.\n")

    # ---- apply to 2026 ---------------------------------------------------
    pr = pd.read_csv(PROJ)
    pr["key_name"] = [player_key(n, p) for n, p in zip(pr.name, pr.pos)]
    hist = (ps.groupby("key_name")
              .agg(hist_mean=("games", "mean"), n_prior=("games", "size")))
    out = pr.merge(hist, on="key_name", how="left")
    out["age_then"] = out.key_name.map(ages)

    # Players with no history or no age fall back to the league mean, which is
    # the honest default given the R2: assume average until told otherwise.
    league_mean = float(d.y.mean())
    have = out.hist_mean.notna() & out.age_then.notna()
    pred = np.full(len(out), league_mean)
    X = np.column_stack([out.loc[have, c].to_numpy(float) for c in cols]
                        + [np.ones(have.sum())])
    pred[have.to_numpy()] = X @ beta
    out["exp_games"] = np.clip(pred, 6.0, FULL)

    # Normalise WITHIN POSITION, over the startable pool only. Two traps here,
    # both of which produced nonsense on the first attempt:
    #  * normalising over all 521 board players uses a denominator dragged down
    #    by deep bench types with thin histories, so nearly every startable
    #    player gets marked UP;
    #  * normalising across positions would compare a quarterback's durability
    #    to a running back's, when what matters is his durability relative to
    #    the other quarterbacks he is being ranked against.
    # The result redistributes projected points by durability within a
    # position and leaves the positional scale untouched.
    # A player with fewer than two seasons has no availability signal — a
    # rookie who appeared in eight games was a rookie, not a fragile veteran.
    # Left at 1.0 the model was marking down Cam Skattebo and Omarion Hampton,
    # both 2025 rookies, as injury risks. No information means no adjustment.
    MIN_SEASONS = 2
    out["avail_mult"] = 1.0
    thin = out.n_prior.fillna(0) < MIN_SEASONS
    for pos, n in CAPS.items():
        at = out[out.pos == pos]
        if at.empty:
            continue
        startable = at.nlargest(min(n, len(at)), "proj").index
        ref = out.loc[startable, "exp_games"].mean()
        if ref > 0:
            out.loc[at.index, "avail_mult"] = (out.loc[at.index, "exp_games"]
                                               / ref)
    out.loc[thin, "avail_mult"] = 1.0
    out["avail_mult"] = out.avail_mult.clip(0.6, 1.15).round(3)
    out["proj_adj"] = (out.proj * out.avail_mult).round(1)

    L.append("## What it changes on the 2026 board\n")
    L.append("`avail_mult` is normalised **within position**, over the "
             "startable pool — so this redistributes projected points by "
             "durability among the players actually competing for the same "
             "slot, rather than shaving everyone or comparing a "
             "quarterback's durability to a running back's.\n")
    L.append(f"Players with fewer than {MIN_SEASONS} seasons of history are "
             f"left untouched at 1.00. A rookie who appeared in eight games "
             f"was a rookie, not a fragile veteran, and the model was "
             f"otherwise marking down 2025 first-year players as injury "
             f"risks ({int(thin.sum())} of {len(out)} board players).\n")
    # Top-60 by raw projection is all quarterbacks; take the startable pool
    # at each position so the movers table spans the board.
    top = pd.concat([out[out.pos == k].nlargest(min(v, (out.pos == k).sum()),
                                                "proj")
                     for k, v in CAPS.items()]).copy()
    top["delta"] = top.proj_adj - top.proj
    L.append("**Marked down most**\n")
    L.append("| player | pos | age | history | exp games | proj | adjusted | Δ |")
    L.append("|---|---|---|---|---|---|---|---|")
    for _, r in top.nsmallest(8, "delta").iterrows():
        L.append(f"| {r['name']} | {r.pos} | {r.age_then:.0f} | "
                 f"{r.hist_mean:.1f} | {r.exp_games:.1f} | {r.proj:.0f} | "
                 f"**{r.proj_adj:.0f}** | {r.delta:+.0f} |")
    L.append("")
    L.append("**Marked up most**\n")
    L.append("| player | pos | age | history | exp games | proj | adjusted | Δ |")
    L.append("|---|---|---|---|---|---|---|---|")
    for _, r in top.nlargest(8, "delta").iterrows():
        L.append(f"| {r['name']} | {r.pos} | {r.age_then:.0f} | "
                 f"{r.hist_mean:.1f} | {r.exp_games:.1f} | {r.proj:.0f} | "
                 f"**{r.proj_adj:.0f}** | {r.delta:+.0f} |")
    L.append("")
    L.append("### How to use this\n")
    L.append("**As a tiebreak, not a board.** At R² = 0.03 the model is barely "
             "better than assuming everyone is average, and it should never "
             "override a real gap in projected points. Where two players are "
             "close, prefer the durable one. Where the adjustment is large "
             "*and* the player sits at a decision point, look at the actual "
             "injury — this model cannot tell an Achilles tear from a "
             "hamstring.\n")

    OUT_PQ.parent.mkdir(parents=True, exist_ok=True)
    out[["key_name", "name", "pos", "exp_games", "avail_mult",
         "proj", "proj_adj"]].to_parquet(OUT_PQ, index=False)
    OUT_MD.write_text("\n".join(L))
    print(f"R2={r2:.4f}  beta={dict(zip(cols, beta.round(3)))} const={beta[-1]:.2f}")
    print(f"Wrote {OUT_MD} and {OUT_PQ}")
    print(out.nlargest(12, "proj")[["name", "pos", "exp_games",
                                    "avail_mult", "proj", "proj_adj"]]
          .to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
