"""A Harper's Index for the league — computed, not written.

    python -m scripts.harpers_index                 # league-shareable
    python -m scripts.harpers_index --sharpness 3   # everyone is fair game
    python -m scripts.harpers_index --out -         # print instead of write

Every figure is derived from the archive at run time. Nothing is hand-typed.

## The form, and how to not get it wrong

Harper's entries are not "a statistic plus its restatement." Two rules, both of
which the first version of this script broke:

1. **The follow-on line is elliptical, and it recontextualizes.** The magazine
   writes "Percentage of Republicans who believe in global warming: 48" and
   then "Who believe in demonic possession: 68" — the second line drops the
   noun phrase and lands somewhere the first did not go. A line that merely
   subtracts the two above it ("Difference: 20") is arithmetic, not irony, and
   is exactly what makes an index read as a list of bullet points.

2. **The strongest pairs are cross-subject.** Two different people, two
   different eras, two different measures — set adjacent so the reader draws
   the conclusion. Three consecutive lines about one manager is a paragraph
   with the verbs removed.

The reader does the work. No entry here explains itself, and none should be
given a sentence of commentary in the output.

Entries are ordered as a developing argument rather than by topic: the format
is strange -> scoring does not buy titles -> the room has a blind spot -> the
market is priced for a different league -> the league's own records are wrong.

Sharpness tiers, since some of these are unkind:
  1  neutral — quirks of the format and the archive
  2  pointed — implies someone got lucky or a market is wrong
  3  brutal  — names a specific manager's specific failure
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import yaml  # noqa: E402

from src.config import get_canonical_name  # noqa: E402
from scripts.rebuild_standings import (  # noqa: E402
    load_history, load_weekly, scoring_system, standings,
)

DRAFT_CACHE = Path("data/draft_cache.json")
CONFIG = Path("config/league.yaml")
VARIANCE = Path("research/variance_study.md")
PROJ = Path("data/inputs/projections.csv")
ADP = Path("data/draft/adp.parquet")
OUT = Path("research/harpers_index.md")

ORDINAL = {1: "1st", 2: "2nd", 3: "3rd", 8: "8th", 9: "9th", 10: "10th"}


class Index:
    def __init__(self, max_sharpness: int):
        self.max = max_sharpness
        self.entries: list[list[tuple[str, str]]] = []

    def add(self, sharpness: int, *lines: tuple[str, str] | None) -> None:
        kept = [ln for ln in lines if ln is not None]
        if sharpness <= self.max and kept:
            self.entries.append(kept)

    def render(self) -> str:
        out = [
            "# A Harper's Index of the League",
            "",
            "*Drawn from 2,420 draft picks (2010–2025), every weekly score both "
            "platforms recorded, and the 2026 board. Generated by "
            "`python -m scripts.harpers_index` — every figure is computed.*",
            "",
            "---",
            "",
        ]
        for lines in self.entries:
            for label, figure in lines:
                out.append(f"{label}: **{figure}**  ")
            out.append("")
        return "\n".join(out)


def _n(v: float, nd: int = 1) -> str:
    s = f"{v:.{nd}f}"
    return s.rstrip("0").rstrip(".") if "." in s else s


def build(max_sharpness: int) -> Index:
    ix = Index(max_sharpness)
    weekly = load_weekly()
    history = load_history()
    cfg = yaml.safe_load(CONFIG.read_text()) or {}
    titles = Counter(h["champion"] for h in history.values() if h.get("champion"))

    # ---------------------------------------------------------------- act 1
    # The format itself is odd, before anyone has drafted a player.
    top_n = cfg.get("top_n_bonus", 5)
    ix.add(1,
           ("Points this league awards for posting the highest score in a week", "1"),
           (f"For posting the {top_n}th-highest", "1"),
           (f"For the {top_n + 1}th", "0"))

    semi = len(cfg.get("semifinal_weeks") or [])
    final = len(cfg.get("final_weeks") or [])
    if semi and final:
        ix.add(1,
               ("Weeks over which this league decides its semifinal", str(semi)),
               ("Over which it decides the championship", str(final)))

    ix.add(1,
           ("Roster spots this league provides for an injured player",
            str(cfg.get("ir_slots", 0))),
           ("Weeks a season lasts", str(cfg.get("regular_season_weeks", 14))))

    # ---------------------------------------------------------------- act 2
    # Points scored and championships won are close to unrelated here.
    pts: dict[str, list[float]] = defaultdict(list)
    seeds: dict[str, list[int]] = defaultdict(list)
    all_reg: list[dict] = []
    for season, rows in weekly.items():
        for r in standings(rows, scoring_system(season) == "dual_points"):
            seeds[r["mgr"]].append(r["seed"])
        for r in rows:
            if not r.get("is_playoff"):
                pts[r["mgr"]].append(r["points"])
                all_reg.append(r)
    order = sorted(pts, key=lambda m: -sum(pts[m]))
    n_mgr = len(order)

    # The last-place scorer with the most rings, against a better scorer with none.
    ranked_titles = [(m, titles.get(m, 0)) for m in order]
    champ_low = next((m for m, t in reversed(ranked_titles)
                      if t == max(titles.values())), None)
    if champ_low:
        low_i = order.index(champ_low)
        better_winless = [m for m in order[:low_i] if not titles.get(m)]
        ix.add(3,
               (f"Rank of {champ_low} among the league's {n_mgr} managers in "
                f"points scored since 2010",
                ORDINAL.get(low_i + 1, f"{low_i + 1}th")),
               ("Championships he has won", str(titles[champ_low])),
               (f"Won by {better_winless[-1]}, who outscores him", "0")
               if better_winless else None)

    # Luck, as two different men rather than one man twice.
    luck: dict[str, tuple[int, int]] = {}
    for m in pts:
        un = lu = 0
        for season, rows in weekly.items():
            reg = [r for r in rows if not r.get("is_playoff")]
            for wk in sorted({r["week"] for r in reg}):
                g = [r for r in reg if r["week"] == wk]
                if len(g) < 4:
                    continue
                med = statistics.median(r["points"] for r in g)
                for r in g:
                    if r["mgr"] != m:
                        continue
                    if r["points"] > med and not r["win"]:
                        un += 1
                    elif r["points"] < med and r["win"]:
                        lu += 1
        luck[m] = (lu, un)
    cursed = max(luck, key=lambda m: luck[m][1])
    blessed = max(luck, key=lambda m: luck[m][0])
    if cursed != blessed:
        ix.add(3,
               (f"Weeks {cursed} has lost while outscoring the league median",
                str(luck[cursed][1])),
               (f"Weeks {blessed} has won while scoring below it",
                str(luck[blessed][0])),
               ("Championships separating them",
                str(abs(titles.get(cursed, 0) - titles.get(blessed, 0)))))

    # One manager owning both extremes is the whole entry.
    hi = max(all_reg, key=lambda r: r["points"])
    lo = min(all_reg, key=lambda r: r["points"])
    ix.add(1,
           ("Highest score any manager has posted in a week",
            f"{_n(hi['points'])} ({hi['season']})"),
           ("Lowest", f"{_n(lo['points'])} ({lo['season']})"),
           ("Managers responsible for both", "1")
           if hi["mgr"] == lo["mgr"] else
           (f"Managers responsible", f"{hi['mgr']} and {lo['mgr']}"))

    # ---------------------------------------------------------------- act 3
    picks = []
    if DRAFT_CACHE.exists():
        picks = json.loads(DRAFT_CACHE.read_text())["drafts"]
        for p in picks:
            p["mgr"] = get_canonical_name(p["platform"], p["manager"])
        seasons = sorted({p["season"] for p in picks})

        r1 = defaultdict(list)
        for p in picks:
            if p["round"] == 1:
                r1[p["mgr"]].append(p["position"])
        rb_count = {m: ps.count("RB") for m, ps in r1.items()}
        top2 = sorted(rb_count, key=lambda m: -rb_count[m])[:2]
        fewest = min(rb_count, key=lambda m: rb_count[m])
        if len(top2) == 2:
            ix.add(1,
                   (f"Times {top2[0]} has opened a draft with a running back, "
                    f"in {len(r1[top2[0]])} seasons", str(rb_count[top2[0]])),
                   (f"Times {top2[1]} has", str(rb_count[top2[1]])),
                   (f"Times {fewest} has", str(rb_count[fewest])))

        recent = seasons[-5:]
        first_qb = [min((p["pick"] for p in picks
                         if p["season"] == s and p["position"] == "QB"), default=None)
                    for s in recent]
        first_qb = [q for q in first_qb if q]
        if first_qb:
            ix.add(1,
                   (f"Quarterbacks taken in the first 19 picks of this league "
                    f"in the last {len(first_qb)} drafts",
                    str(sum(1 for q in first_qb if q <= 19))),
                   ("Earliest any has gone", f"pick {min(first_qb)}"))

        champ_qb = []
        for s, h in history.items():
            c = h.get("champion")
            rs = [p["round"] for p in picks if p["season"] == s
                  and p["mgr"] == c and p["position"] == "QB"]
            if rs:
                champ_qb.append(min(rs))
        if champ_qb:
            ix.add(1,
                   ("Median round in which a champion of this league has "
                    "drafted his quarterback", str(int(statistics.median(champ_qb)))),
                   ("Champions who took one in the first two rounds",
                    str(sum(1 for r in champ_qb if r <= 2))))

        # A single-line oddity: no pairing needed.
        jg = [p for p in picks if p["mgr"] == "James Galante"]
        one_qb = sum(1 for s in seasons
                     if sum(1 for p in jg if p["season"] == s
                            and p["position"] == "QB") == 1)
        ix.add(1,
               (f"Drafts, of {len(seasons)}, in which James Galante has taken "
                f"exactly one quarterback", str(one_qb)))

    # ---------------------------------------------------------------- act 4
    if PROJ.exists():
        import pandas as pd
        pr = pd.read_csv(PROJ)
        qb = pr[pr.pos == "QB"].nlargest(1, "proj")
        if len(qb) and "fp_proj_4pt" in pr.columns:
            r = qb.iloc[0]
            ix.add(2,
                   (f"Points the consensus projects for {r['name']} in 2026",
                    _n(r["fp_proj_4pt"])),
                   ("Points he scores under this league's rules", _n(r["proj"])))
        if ADP.exists():
            adp = pd.read_parquet(ADP)
            repl = {p: pr[pr.pos == p].nlargest(n, "proj")["proj"].iloc[-1]
                    for p, n in (("QB", 10), ("RB", 27), ("WR", 30), ("TE", 13))
                    if len(pr[pr.pos == p]) >= n}
            m = pr[pr.pos.isin(repl)].copy()
            m["vor"] = m.proj - m.pos.map(repl)
            m = (m.sort_values("vor", ascending=False).reset_index(drop=True)
                   .merge(adp[["name", "adp"]], on="name", how="left"))
            tq = m[m.pos == "QB"].head(1)
            if len(tq) and pd.notna(tq.iloc[0]["adp"]):
                r = tq.iloc[0]
                rank = int(m.index[m.name == r["name"]][0]) + 1
                ix.add(2,
                       (f"Rank of {r['name']} among all players by value in "
                        f"this league", str(rank)),
                       ("Average pick at which the market takes him",
                        _n(r["adp"], 0)))
            te = m[(m.pos == "TE") & m.adp.notna()].head(2)
            slot = cfg.get("my_draft_slot")
            teams = cfg.get("teams", 10)
            if len(te) == 2 and slot:
                # Snake wrap for a given slot: at the turn of round 2k the
                # manager picks back-to-back at (2*teams*k - slot + 1, 2*teams*k
                # + slot). For slot 1 in a 10-team league that is 20/21, 40/41.
                wraps = [(2 * teams * k - slot + 1, 2 * teams * k + slot)
                         for k in range(1, cfg.get("rounds", 15) // 2 + 1)]
                pair = min(wraps, key=lambda w: abs(w[0] - te.adp.mean()))
                ix.add(2,
                       ("Average picks at which the two most valuable tight "
                        "ends on the board are taken",
                        f"{_n(te.iloc[0]['adp'], 0)} and {_n(te.iloc[1]['adp'], 0)}"),
                       ("Consecutive picks James Galante holds just before them",
                        f"{pair[0]} and {pair[1]}"))

    # Variance study: parsed rather than retyped, so it cannot drift.
    if VARIANCE.exists():
        txt = VARIANCE.read_text()
        a = re.search(r"worth \*\*\+?([\d.]+) percentage points", txt)
        b = re.search(r"just \*\*\+?([\d.]+) ± [\d.]+ percentage points", txt)
        if a and b:
            ix.add(1,
                   ("Percentage points of championship probability bought by "
                    "one extra point per week", a.group(1)),
                   ("Bought by the widest swing in weekly volatility this "
                    "league has ever produced", b.group(1)))

    # ---------------------------------------------------------------- act 5
    wrong = sum(1 for h in history.values()
                if "WRONG" in (h.get("notes") or "").upper())
    unver = sum(1 for h in history.values() if not h.get("verified"))
    ix.add(1,
           ("Seasons of this league the platforms have on record", str(len(history))),
           ("Seasons for which they name the wrong champion",
            f"{wrong} that can be proved"),
           ("Champions in the league's corrected records confirmed by a living "
            "person", str(len(history) - unver)))

    if picks:
        rep_rate: dict[str, float] = {}
        for m in pts:
            mine = [p for p in picks if p["mgr"] == m]
            tot = same = 0
            for s in seasons:
                if s - 1 not in seasons:
                    continue
                prev = {p["player_name"] for p in mine if p["season"] == s - 1}
                cur = [p for p in mine if p["season"] == s]
                tot += len(cur)
                same += sum(1 for p in cur if p["player_name"] in prev)
            if tot:
                rep_rate[m] = 100 * same / tot
        if rep_rate:
            least = min(rep_rate, key=lambda m: rep_rate[m])
            counts = Counter(p["player_name"] for p in picks if p["mgr"] == least)
            fav, n = counts.most_common(1)[0]
            ix.add(2,
                   (f"Rate at which {least} re-drafts his own player from the "
                    f"previous season, the lowest of {n_mgr}",
                    f"{_n(rep_rate[least])}%"),
                   (f"Times he has drafted {fav}", str(n)))
    return ix


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sharpness", type=int, default=2, choices=(1, 2, 3))
    ap.add_argument("--out", default=str(OUT), help="'-' for stdout")
    a = ap.parse_args()
    ix = build(a.sharpness)
    text = ix.render()
    if a.out == "-":
        print(text)
    else:
        Path(a.out).parent.mkdir(parents=True, exist_ok=True)
        Path(a.out).write_text(text)
        print(f"Wrote {len(ix.entries)} entries (sharpness <= {a.sharpness}) "
              f"-> {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
