"""A Harper's Index for the league — ironic juxtapositions, computed not written.

    python -m scripts.harpers_index                 # league-shareable
    python -m scripts.harpers_index --sharpness 3   # everyone is fair game
    python -m scripts.harpers_index --out -         # print instead of write

Every figure here is derived from the archive at run time, so the Index can be
regenerated each season and will never drift from the data. Nothing is
hand-typed. If a number looks wrong, the generator is wrong.

The format's rule is that the juxtaposition does the work: two or three bare
figures, adjacent, no commentary. Anything that needs a sentence of
explanation to land does not belong here.

Sharpness tiers, since some of these are unkind:
  1  neutral — quirks of the format and the archive
  2  pointed — implies someone got lucky or a market is wrong
  3  brutal  — names a specific manager's specific failure

The material is unusually good because this league's own records disagree with
what the platforms recorded: the regular season is dual-points (which ESPN
could not represent) and ESPN names the wrong champion in at least three
seasons. Several ironies below are therefore invisible to everyone in the
league.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.config import get_canonical_name  # noqa: E402
from scripts.rebuild_standings import (  # noqa: E402
    load_history, load_weekly, scoring_system, standings,
)

DRAFT_CACHE = Path("data/draft_cache.json")
OUT = Path("research/harpers_index.md")
PROJ = Path("data/inputs/projections.csv")
ADP = Path("data/draft/adp.parquet")

SLEEPER_ERA = 2024  # Sleeper-era seasons; ESPN weeks are pre-2024


class Index:
    def __init__(self, max_sharpness: int):
        self.max = max_sharpness
        self.entries: list[tuple[int, list[tuple[str, str]]]] = []

    def add(self, sharpness: int, *lines: tuple[str, str]) -> None:
        """Add one entry: a run of (label, figure) pairs read in sequence."""
        if sharpness <= self.max:
            self.entries.append((sharpness, list(lines)))

    def render(self) -> str:
        out = ["# A Harper's Index of the League",
               "",
               "*Figures are drawn from 2,420 draft picks (2010-2025), every "
               "weekly score both platforms recorded, and the 2026 board. "
               "Generated by `python -m scripts.harpers_index` — every number "
               "is computed, none are typed.*",
               ""]
        for _, lines in self.entries:
            for label, figure in lines:
                out.append(f"**{label}:** {figure}  ")
            out.append("")
        return "\n".join(out)


def _fmt(v: float, nd: int = 1) -> str:
    return f"{v:.{nd}f}".rstrip("0").rstrip(".") if nd else f"{v:.0f}"


def build(max_sharpness: int) -> Index:
    ix = Index(max_sharpness)
    weekly = load_weekly()
    history = load_history()
    champs = {s: h.get("champion") for s, h in history.items() if h.get("champion")}
    title_count: dict[str, int] = defaultdict(int)
    for c in champs.values():
        title_count[c] += 1

    # ---- per-season standings, seeds, and weekly rows --------------------
    seeds: dict[str, list[int]] = defaultdict(list)
    top5_total: dict[str, int] = defaultdict(int)
    all_rows: list[dict] = []
    for season, rows in weekly.items():
        tbl = standings(rows, scoring_system(season) == "dual_points")
        for r in tbl:
            seeds[r["mgr"]].append(r["seed"])
            top5_total[r["mgr"]] += r["top5"]
        all_rows += [r for r in rows if not r.get("is_playoff")]

    managers = sorted(seeds)
    pts: dict[str, list[float]] = defaultdict(list)
    for r in all_rows:
        pts[r["mgr"]].append(r["points"])

    # ---- 1. scoring rank vs. silverware (Sleeper era, same schedule) -----
    era = [r for r in all_rows if r["season"] >= SLEEPER_ERA]
    era_pts: dict[str, list[float]] = defaultdict(list)
    for r in era:
        era_pts[r["mgr"]].append(r["points"])
    era_rank = sorted(era_pts, key=lambda m: -statistics.mean(era_pts[m]))
    if len(era_rank) >= 2:
        best, worst = era_rank[0], era_rank[-1]
        ix.add(2,
               (f"Rank of {best} in points per week since {SLEEPER_ERA}", "1"),
               (f"Rank of {worst}", f"{len(era_rank)}"),
               ("Points per week separating them",
                _fmt(statistics.mean(era_pts[best]) - statistics.mean(era_pts[worst]))))

    # ---- 2. luck: above-median losses vs below-median wins ---------------
    luck: dict[str, tuple[int, int]] = {}
    for m in managers:
        unlucky = lucky = 0
        for season, rows in weekly.items():
            reg = [r for r in rows if not r.get("is_playoff")]
            for wk in sorted({r["week"] for r in reg}):
                games = [r for r in reg if r["week"] == wk]
                if len(games) < 4:
                    continue
                med = statistics.median(r["points"] for r in games)
                for r in games:
                    if r["mgr"] != m:
                        continue
                    if r["points"] > med and not r["win"]:
                        unlucky += 1
                    elif r["points"] < med and r["win"]:
                        lucky += 1
        luck[m] = (unlucky, lucky)
    luckiest = max(luck, key=lambda m: luck[m][1] - luck[m][0])
    unluckiest = min(luck, key=lambda m: luck[m][1] - luck[m][0])
    ix.add(3,
           (f"Weeks {luckiest} has won while scoring below the league median",
            str(luck[luckiest][1])),
           (f"Weeks he has lost while scoring above it", str(luck[luckiest][0])),
           ("Championships he has won", str(title_count.get(luckiest, 0))))
    ix.add(2,
           (f"Weeks {unluckiest} has lost while outscoring the median",
            str(luck[unluckiest][0])),
           ("Championships he has won", str(title_count.get(unluckiest, 0))))

    # ---- 3. the never-champion vs a repeat champion ----------------------
    winless = [m for m in managers if not title_count.get(m)]
    repeat = [m for m in managers if title_count.get(m, 0) >= 3]
    if winless and repeat:
        w = min(winless, key=lambda m: statistics.mean(seeds[m]))
        r = max(repeat, key=lambda m: statistics.mean(seeds[m]))
        # Only worth printing if the irony actually holds — i.e. the manager
        # who has never won finishes HIGHER on average than a repeat champion.
        # Emitting it unconditionally produced "6.6 vs 5.9", which says the
        # opposite of what the juxtaposition implies.
        if statistics.mean(seeds[w]) < statistics.mean(seeds[r]):
            ix.add(3,
                   (f"Average regular-season finish of {w}, who has never won",
                    _fmt(statistics.mean(seeds[w]))),
                   (f"Average finish of {r}, who has won {title_count[r]}",
                    _fmt(statistics.mean(seeds[r]))))

    # ---- 4. top-5 weekly finishes vs titles ------------------------------
    most_top5 = max(top5_total, key=lambda m: top5_total[m])
    ix.add(2,
           (f"Weeks {most_top5} has finished in the league's top five scorers — "
            f"more than anyone", str(top5_total[most_top5])),
           ("Championships that has produced", str(title_count.get(most_top5, 0))))

    # ---- 5. the archive is wrong -----------------------------------------
    wrong = [s for s, h in history.items()
             if "WRONG" in (h.get("notes") or "").upper()]
    unverified = [s for s, h in history.items() if not h.get("verified")]
    ix.add(1,
           ("Seasons this league has played", str(len(history))),
           ("Seasons for which ESPN records the wrong champion",
            str(len(wrong)) + " that we can prove"),
           ("Champions in this file confirmed by a human being",
            str(len(history) - len(unverified))))

    # ---- 6. draft tendencies ---------------------------------------------
    if DRAFT_CACHE.exists():
        picks = json.loads(DRAFT_CACHE.read_text())["drafts"]
        for p in picks:
            p["mgr"] = get_canonical_name(p["platform"], p["manager"])
        seasons = sorted({p["season"] for p in picks})

        # round-1 position monomania
        r1: dict[str, list[str]] = defaultdict(list)
        for p in picks:
            if p["round"] == 1:
                r1[p["mgr"]].append(p["position"])
        mono, n_rb, n_yrs = None, 0, 0
        for m, ps in r1.items():
            c = ps.count("RB")
            if c > n_rb:
                mono, n_rb, n_yrs = m, c, len(ps)
        if mono:
            ix.add(1,
                   (f"Times {mono} has opened his draft with a running back, "
                    f"in {n_yrs} seasons", str(n_rb)))

        # repeat picks: least loyal manager who nonetheless has a favourite
        rep_rate: dict[str, float] = {}
        favourites: dict[str, tuple[str, int]] = {}
        for m in managers:
            mine = [p for p in picks if p["mgr"] == m]
            tot = same = 0
            for s in seasons:
                if s - 1 not in seasons:
                    continue
                prev = {p["player_name"] for p in mine if p["season"] == s - 1}
                cur = [p for p in mine if p["season"] == s]
                tot += len(cur)
                same += sum(1 for p in cur if p["player_name"] in prev)
            if tot:
                rep_rate[m] = 100 * same / tot
            counts = defaultdict(int)
            for p in mine:
                counts[p["player_name"]] += 1
            if counts:
                best = max(counts.items(), key=lambda kv: kv[1])
                favourites[m] = best
        if rep_rate:
            least = min(rep_rate, key=lambda m: rep_rate[m])
            most = max(rep_rate, key=lambda m: rep_rate[m])
            fav, n = favourites.get(least, ("-", 0))
            ix.add(2,
                   (f"Rate at which {least} re-drafts his own player from last "
                    f"season — lowest in the league", f"{_fmt(rep_rate[least])}%"),
                   (f"Rate for {most}", f"{_fmt(rep_rate[most])}%"),
                   (f"Times {least} has nonetheless drafted {fav}", str(n)))

        # the QB market
        qb_first: list[int] = []
        for s in seasons[-5:]:
            qbs = [p["pick"] for p in picks
                   if p["season"] == s and p["position"] == "QB"]
            if qbs:
                qb_first.append(min(qbs))
        if qb_first:
            ix.add(1,
                   ("Quarterbacks taken in the first 19 picks of this league "
                    f"in the last {len(qb_first)} drafts",
                    str(sum(1 for q in qb_first if q <= 19))),
                   ("Earliest any quarterback has gone in that span",
                    f"pick {min(qb_first)}"))

        # champions' first QB
        rounds = []
        for s, c in champs.items():
            qs = [p["round"] for p in picks
                  if p["season"] == s and p["mgr"] == c and p["position"] == "QB"]
            if qs:
                rounds.append(min(qs))
        if rounds:
            ix.add(1,
                   ("Median round in which a champion of this league drafted "
                    "his quarterback", str(int(statistics.median(rounds)))),
                   ("Champions who took one in the first two rounds",
                    str(sum(1 for r in rounds if r <= 2))))

    # ---- 7. the 2026 board -----------------------------------------------
    if PROJ.exists():
        import pandas as pd
        pr = pd.read_csv(PROJ)
        qb = pr[pr.pos == "QB"].nlargest(1, "proj")
        if len(qb) and "fp_proj_4pt" in pr.columns:
            r = qb.iloc[0]
            ix.add(1,
                   (f"Points FantasyPros projects for {r['name']} in 2026",
                    _fmt(r["fp_proj_4pt"])),
                   ("Points he scores under this league's rules",
                    _fmt(r["proj"])),
                   ("Difference, in a league decided by two-week totals",
                    _fmt(r["proj"] - r["fp_proj_4pt"])))
        if ADP.exists():
            adp = pd.read_parquet(ADP)
            # Rank value over the FULL projection pool, then attach ADP. An
            # inner join first would shrink the pool to only players the market
            # prices, quietly shifting every rank.
            repl = {p: pr[pr.pos == p].nlargest(n, "proj")["proj"].iloc[-1]
                    for p, n in (("QB", 10), ("RB", 27), ("WR", 30), ("TE", 13))
                    if len(pr[pr.pos == p]) >= n}
            m = pr[pr.pos.isin(repl)].copy()
            m["vor"] = m.proj - m.pos.map(repl)
            m = m.merge(adp[["name", "adp"]], on="name", how="left")
            m = m.sort_values("vor", ascending=False).reset_index(drop=True)
            top_qb = m[m.pos == "QB"].head(1)
            if len(top_qb):
                r = top_qb.iloc[0]
                rank = int(m.index[m.name == r["name"]][0]) + 1
                ix.add(1,
                       (f"Rank of {r['name']} among all players by value over "
                        "replacement", str(rank)),
                       ("Average pick at which the market takes him",
                        _fmt(r["adp"])))
            # steepest cliff at the top of a position
            for pos, label in (("TE", "tight end"),):
                s = m[m.pos == pos].head(4)
                if len(s) >= 3:
                    ix.add(1,
                           (f"Points of value over replacement between the "
                            f"best {label} available and the third-best",
                            _fmt(s.iloc[0]["vor"] - s.iloc[2]["vor"])),
                           ("Picks between them on the board",
                            _fmt(s.iloc[2]["adp"] - s.iloc[0]["adp"])))

    # ---- 8. extremes ------------------------------------------------------
    best_week = max(all_rows, key=lambda r: r["points"])
    worst_week = min(all_rows, key=lambda r: r["points"])
    ix.add(1,
           ("Highest score anyone has posted in a week",
            f"{_fmt(best_week['points'])} ({best_week['mgr']}, "
            f"{best_week['season']})"),
           ("Lowest", f"{_fmt(worst_week['points'])} ({worst_week['mgr']}, "
                      f"{worst_week['season']})"))

    # Most points vs most titles. Only ironic when they are different people;
    # when the same manager leads both, the entry says nothing.
    all_time = sorted(pts, key=lambda m: -sum(pts[m]))
    leader = all_time[0]
    best_n = max(title_count.values())
    tied = sorted(m for m, n in title_count.items() if n == best_n)
    # Three managers share the record at 3 titles; naming just one of them
    # (whatever max() happens to return) would be false.
    most_titles = tied[0] if len(tied) == 1 else \
        f"{len(tied)} managers, tied on {best_n}"
    if len(tied) == 1 and leader != most_titles:
        ix.add(2,
               (f"Rank of {leader} in points scored across all "
                f"{len(weekly)} seasons", "1"),
               ("Championships", str(title_count.get(leader, 0))),
               (f"Championships won by {most_titles}",
                str(title_count[most_titles])))
    else:
        runner = all_time[1] if len(all_time) > 1 else None
        if runner:
            ix.add(1,
                   (f"Manager who has scored the most points in "
                    f"{len(weekly)} seasons", leader),
                   (f"Championships won by him", str(title_count.get(leader, 0))),
                   (f"Managers tied with him on that total",
                    str(len(tied) - 1) if leader in tied else "0"),
                   ("Points separating him from the next-highest scorer",
                    _fmt(sum(pts[leader]) - sum(pts[runner]))))
    return ix


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sharpness", type=int, default=2, choices=(1, 2, 3),
                    help="1 neutral, 2 pointed (default), 3 brutal")
    ap.add_argument("--out", default=str(OUT), help="'-' for stdout")
    a = ap.parse_args()

    ix = build(a.sharpness)
    text = ix.render()
    if a.out == "-":
        print(text)
    else:
        Path(a.out).parent.mkdir(parents=True, exist_ok=True)
        Path(a.out).write_text(text)
        print(f"Wrote {len(ix.entries)} entries (sharpness <= {a.sharpness}) "
              f"-> {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
